### ISSUE TITLE
No sound while playing files off network share.

### ISSUE THREAD

**Issue by klokop** [woutervanwijk/Pi-MusicBox#108]
Tried both webinterface and local mpc, and they show a file is playing. However, nothing can be heard. Files on the actual SD card play fine.

- user mopidy has access to share, and files in share.
- network is up.
- volume is on.
- tried a bunch of different files.
- can play music from iTunes over airport.

Sometimes if I click anywhere on the progress indicator of the file that is playing, I can hear a very short burst of sound.

Is this a network issue?

**Comment by kingosticks** [comment]
Assumed not - closing.
