### ISSUE TITLE
Port to a different hardware platform

### ISSUE THREAD

**Issue by dieserkai** [woutervanwijk/Pi-MusicBox#125]
Hey,

the raspi is a nice piece of hardware, but there are a few points which could be better.

The two main problems are the slow cpu and the size of the ram.
There are various other board with a faster cpu and more Ram. The Cubieboard 1 (released 2 years ago) comes with a 1Ghz CPU and 1GB RAM and a SATA port. Also it does have a nand storage for the OS.

Full specs: http://docs.cubieboard.org/

This board is at the same price level as the pi and brings more power.

I think the software can benefit from this.(directly attached sata drive as storage for the audio files, maybe some speed improvements for the UI)

Are there any plans to bring the software up and running on a different hardware system?

Kai

**Comment by kingosticks** [comment]
No reply so closing. Once we get things packaged this will be supported.
