### ISSUE TITLE
Local files metadata (Artist, Album, ...) not detected during scan

### ISSUE THREAD

**Issue by amitkot** [woutervanwijk/Pi-MusicBox#126]
I have an external HD connected via USB to the Raspberry Pi.
The external HD is mounted under /media/WDUSB, with the following parameters:
```
UUID=...	/media/WDUSB	ntfs-3g	rw,defaults	0	0
```
I also created a symlink connecting the music directory on the external drive as a directory inside ```/music``` where mopidy is configured to look for local files, using:
```bash
ln -s /media/WDUSB/Music /music/MusicBox/WDUSB
```

I can play music from the external drive, and it kind of works ok.

The problem is that the files are not scanned correctly for Artist, Album, Song name, etc.
They can be played as files, but there is no way to find them in a search, or browse for an Artist albums.

Any idea why this might happen, or how to start debugging it?

**Comment by kingosticks** [comment]
Musicbox now uses the excellent SQL local library by default. This should solve these problems but reopen if not.
