### ISSUE TITLE
Wifi issue with 0.5

### ISSUE THREAD

**Issue by remcohe** [woutervanwijk/Pi-MusicBox#129]
My USB-N10 wifi adapter works fine with 0.4.3 but I cannot get it to work with 0.5. 
I get the same errors others see in 0.5 beta 1 https://github.com/woutervanwijk/Pi-MusicBox/issues/99 and when I plug in the ethernet cable it works fine. But in the room where I use the Pi I have no ethernet.

I tried to edit /etc/network/interfaces to change the ethernet settings but vi also doesn't work :$

**Comment by jenkinzz** [comment]
Noob here—how does one locate and edit that file? I'm on 0.5.2 and having the same problems. I tried connecting a keyboard +screen and entering the commands as the command line text was scrolling, but nothing happened

**Comment by satzg** [comment]
I hooked it up to a wired ethernet and ssh into it. I also connected a monitor and keyboard and logged in once it booted up.

Thanks,
Greg
