### ISSUE TITLE
Mopidy and aplay uses USB sound card but Shairport uses analog

### ISSUE THREAD

**Issue by C-Duv** [woutervanwijk/Pi-MusicBox#149]
I'm using an *Enermax DreamBass AP001* USB sound card recognized by `lsusb` as follows:

    Bus 001 Device 004: ID 040d:3400 VIA Technologies, Inc.

Mopidy radio and local/network files playback works fine on v0.5 without any changes (`output` left to blank/autodetect with: `output = `): it uses the USB sound card.
But Airplay (from iOS) playback uses the analog output.

I've found some similar issue (not on a Pi Music Box setup tough): [Cannot get Shairport working with USB soundcard](http://www.raspberrypi.org/forums/viewtopic.php?f=38&t=15135) and the advised command:

```
amixer cset numid=3 1
```

followed by a reboot seems to have done the trick: both Mopidy/Shairport now use the USB sound card.

I'm posting it here for future reference and in case it breaks tomorrow ;)

Here are some aplay outputs:

 `aplay -l`:

    **** List of PLAYBACK Hardware Devices ****
    card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
      Subdevices: 8/8
      Subdevice #0: subdevice #0
      Subdevice #1: subdevice #1
      Subdevice #2: subdevice #2
      Subdevice #3: subdevice #3
      Subdevice #4: subdevice #4
      Subdevice #5: subdevice #5
      Subdevice #6: subdevice #6
      Subdevice #7: subdevice #7
    card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
      Subdevices: 1/1
      Subdevice #0: subdevice #0
    card 1: Dongle [VIA USB Dongle], device 0: USB Audio [USB Audio]
      Subdevices: 0/1
      Subdevice #0: subdevice #0
    card 2: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 []
      Subdevices: 1/1
      Subdevice #0: subdevice #0

 `aplay -L`:

    null
        Discard all samples (playback) or generate zero samples (capture)
    sysdefault:CARD=ALSA
        bcm2835 ALSA, bcm2835 ALSA
        Default Audio Device
    sysdefault:CARD=Dongle
        VIA USB Dongle, USB Audio
        Default Audio Device
    front:CARD=Dongle,DEV=0
        VIA USB Dongle, USB Audio
        Front speakers
    surround40:CARD=Dongle,DEV=0
        VIA USB Dongle, USB Audio
        4.0 Surround output to Front and Rear speakers
    surround41:CARD=Dongle,DEV=0
        VIA USB Dongle, USB Audio
        4.1 Surround output to Front, Rear and Subwoofer speakers
    surround50:CARD=Dongle,DEV=0
        VIA USB Dongle, USB Audio
        5.0 Surround output to Front, Center and Rear speakers
    surround51:CARD=Dongle,DEV=0
        VIA USB Dongle, USB Audio
        5.1 Surround output to Front, Center, Rear and Subwoofer speakers
    surround71:CARD=Dongle,DEV=0
        VIA USB Dongle, USB Audio
        7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
    iec958:CARD=Dongle,DEV=0
        VIA USB Dongle, USB Audio
        IEC958 (S/PDIF) Digital Audio Output
    sysdefault:CARD=sndrpihifiberry
        snd_rpi_hifiberry_dac,
        Default Audio Device

**Comment by kingosticks** [comment]
Since no reply I'll close this.reopen if its still a problem.
