### ISSUE TITLE
No sound on Raspberry over analog

### ISSUE THREAD

**Issue by BeTZe** [woutervanwijk/Pi-MusicBox#152]
Hello,
i have a problem. I installed MusicBox and it starts clear. I can use the webfrontend to config or to search for music.
My Problem is, that i dont get sound when i use the analog output. Nothing comes. I know use two different SD Cards and two different rasperrys. All the same.

I found this:
https://github.com/woutervanwijk/Pi-MusicBox/issues/19

But this help also not.

What can i do more?

**Comment by kingosticks** [comment]
Assumed not, closing.

**Comment by PranitModak** [comment]
Hi @kingosticks  @woutervanwijk  

aplay /usr/share/sounds/alsa/Front_Center.wav is giving loud audio output through my analog output.

Also fyi mopidy analog output was working when I manually installed it.

musicbox seems to unable to output any audio.
Can you please help ?

**Comment by PranitModak** [comment]
output of aplay -l

root@MusicBox:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
