### ISSUE TITLE
Sign-in Attempt Prevented By Google

### ISSUE THREAD

**Issue by evosyn** [woutervanwijk/Pi-MusicBox#178]
Hi, cross posting this here because I'm unsure if I have solved this in the best way possible.

I was having issues connecting to google music, so I ended up enabling access for less secure apps under my google security settings. Is this the best course of action in this case? Or should I be able to block access for less secure apps and still access my google music. I have device ID left blank in my config settings. Adding my either my google services ID or my android ID both result in no login attempt.

Here's a copy of my full description of the problem:

> I'm attempting to use Pi Musicbox on a Raspberry Pi B+. I've put my username and password into the config file, but I cannot get Musicbox to load data from my all access account. Upon further inspection, I noticed google was blocking login attempts ( https://security.google.com/settings/security/activity?hl=en ). This happens if I supply my username and password, but no device ID. If I DO supply the device ID, nothing happens (no data from account, and no warning of an unauthorized login attempt).

> I have marked each attempt as my own activity in google's security tab.

I'm using Pi Music box .5 and .5.1beta

Thanks

**Comment by Pindar** [comment]
I had some problems with authentication too. Here my workaround (not 100% if this the same problem - hope it helps somebody though):

1. `apt-get install -y python-crypto`
1. `pip install --upgrade --no-deps gpsoauth`
1. `pip install --upgrade --no-deps mopidy-gmusic`
1. `pip install --upgrade --no-deps gmusicapi`
1. replace "wheezy" for "jessie" in sources.list and other files in sources.list.d directory. 
1. `apt-get install --no-install-recommends python2.7-minimal`
1. reboot

**Comment by kingosticks** [comment]
I'm going to close this since there's been response from the OP.

Thanks for your update @Pindar . Steps 5 and 6 sound a little weird and I would just warn anyone following this to perhaps first try just doing the first 4 steps.

**Comment by Pindar** [comment]
@kingosticks yes i have to admit that it's not the obvious way and probably there is a better way to enable SNI. The problem for me was that the authentication failed while checking the certificate without 5+6. On Stackoverflow I found an article which says that only phython 2.7.9 (http://stackoverflow.com/questions/30652989/python-requests-sslerror?answertab=votes#tab-top) supports SNI. So I looked for a easy way to upgrade just python and followed the instruction on https://www.reddit.com/r/raspberry_pi/comments/33ti0k/how_do_you_upgrade_python_273_to_279_on_raspbian/ but didn't wont to upgrade the entire system (no apt-get dist-upgrade) but just installed the new python. You can actually change jessie back to wheeze after the python upgrade. 

I hope the workaround is comprehensible with this extra info.

**Comment by kingosticks** [comment]
Ahhh ok. Cheers for clarifying that.
