### ISSUE TITLE
Including squeezelite

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [woutervanwijk/Pi-MusicBox#191]
Would it be difficult to have squeezelite included in future versions of Pi-MusicBox? It would nicely integrate with my Squeezebox setup.

Will it break things if I install it manually now?

**Comment by SplatManDK** [comment]
This was closed 4 years ago., and things have changed. Raspberry 2 and 3 are a significant upgrade over 2014 hardware. Any chance this could get re-opened? Or do I post a new feature request? :-)
