### ISSUE TITLE
Disk corrupted when changing settings - 0.5.1

### ISSUE THREAD

**Issue by teq0** [woutervanwijk/Pi-MusicBox#196]
About 2 out of every 3 times I make a change in the settings UI when the device reboots it gets stuck during boot up because the disk has been corrupted and needs the root password entered in order to do a manual fsck. I've tried a number of SD cards, I don't believe it's a hardware problem.

**Comment by driesken** [comment]
Also experienced this problem today. Was a fresh musicbox 0.5.2 install and all I did was mount a share for the first time, containing 16000+ mp3's. The indexing was almost at the end when the musicbox suddenly crashed and threw that same error at me.

The FSCKFIX=yes did the trick.

**Comment by dereitz** [comment]
I just hit this myself today, so add one more confirmation of this issue.  I did a fresh installation for the first time of Musicbox the day before yesterday (0.5.2).

**Comment by PiPietje** [comment]
A few days ago MusicBox (0.5.2 with FSCKFIX=Yes)) didn't boot so I connect a screen and there was a message that the systeem was read-only and a of course a manual FSCK wasn't possible.....so no music that morning at my work

**Comment by daveh19** [comment]
Wow am I glad to come across this bug report. I've been running in headless mode so it's been nigh on impossible to figure out what was wrong with my system, but with Wooter's suggestion (fsckfix=yes) my musicbox is finally working again.

To help pin the issue down, have any of the rest of you the following in your dmesg output?
[   15.563749] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.

It's coming up every single time for me, even when I type 'reboot' from the ssh command promt.

**Comment by woutervanwijk** [comment]
the error in dmesg has to do with the dirty-bit. See http://www.raspberrypi.org/forums/viewtopic.php?p=495156

**Comment by grexx** [comment]
same disk corruption issue at boot with 0.5.2
tryied with different power supply and sdcard.
only happen after remounting the sdcard on my laptop.
fsckfix=yes solved the problem

**Comment by woutervanwijk** [comment]
Hopefully this is fixed in 0.5.3: http://pimusicbox.com/musicbox0.5.3.zip

**Comment by PiPietje** [comment]
Wouter,

Yesterdag I have installed the 0.5.3. image, just the ould way. Download, unzip, edit the settings, edit streamuris and finally put the sdcard in the Pi and.........it boot without errors

THX

**Comment by driesken** [comment]
Have also installed 0.5.3, issue seems to be gone. Thanks!

**Comment by kingosticks** [comment]
Seems this is fixed then.
