### ISSUE TITLE
HifiBerry Digi & Pi MusicBox 0.5.2

### ISSUE THREAD

**Issue by aschneider** [woutervanwijk/Pi-MusicBox#201]
Hi there -
first of all - many thanks for this awesome project, we are really enyoing the Pi MusicBox combined with an Hifiberry Digi on a (old) Raspberry PI Model B. Keep up the good work!

One issue still seems to be that the HifiBerry Digi can only be used when manually switching the card in the asound.conf from "0" to "1" for it to work. However since being overridden on reboot that solution is not ideal:

root@MusicBox:~# cat /etc/asound.conf
pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw
    card 1
}

The reason must be that the HifiBerry Digi is not recognized as card "0" on the raspberry PI:

root@MusicBox:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sndrpihifiberry [snd_rpi_hifiberry_digi], device 0: HifiBerry Digi HiFi wm8804-spdif-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0

I have seen this issue being reported in an older (closed) thread: 
https://github.com/woutervanwijk/Pi-MusicBox/issues/100

Now the reason why I created a new one is that (staring with 0.5.1 I believe) you can actually select the HifiBerry Digi as Sound Device in Audio Settings - so I am assuming that setting should do the "change" I am still required to do manually and therefore can be considered as a bug?

Would be great if this could be improved - though its definitely not the most urgent issue :)

**Comment by Znegl** [comment]
This didn't work for me. I just ended up with a Pi that restarted every time i tried to play a stream.

**Comment by Nachhall** [comment]
Are there any new on MusicBox with Hifiberry Digi? I have a Digi+ myself and cannot get it running.

**Comment by kingosticks** [comment]
Is this fixed with the recent update to setsound.sh?

```
curl https://raw.githubusercontent.com/woutervanwijk/Pi-MusicBox/master/filechanges/opt/musicbox/setsound.sh > /opt/musicbox/setsound.sh
chmod +x /opt/musicbox/setsound.sh
```

**Comment by kingosticks** [comment]
Reopen if not.
