### ISSUE TITLE
Scrobbling fails

### ISSUE THREAD

**Issue by liftarn** [woutervanwijk/Pi-MusicBox#204]
It seems no tracks are scrobbled to Last.fm since I updated to 0.5.2
The tracks are displayed as "Listening now" so the communication seem to be OK.
I have tried other music players and there the tracks are scrobbled OK.
I play tracks from Google Music.

**Comment by kingosticks** [comment]
This sounds like https://github.com/mopidy/mopidy-scrobbler/issues/6

**Comment by liftarn** [comment]
Very much like that yes.

**Comment by woutervanwijk** [comment]
Much like that indeed. Closing here.
