### ISSUE TITLE
Mention that Spotifty Connect isn't implemented

### ISSUE THREAD

**Issue by calgot** [woutervanwijk/Pi-MusicBox#205]
I just bought a PI and installed MusicBox, after reading about Fon Gramofon. While it isn't explicitly mentioned, I led myself to believe that the MusicBox also supported Spotify Connect. Embarrasing mistake by me of course, but perhaps a small note that Spotify Connect isn't supported could be added to the webpage / documentation?

I realize you're waiting for Spotify to release the API for this, I really hope they will do that soon. We have several Spotify users in the family, each with a different account, so currently MusicBox isn't really an option for me unfortunately.

**Comment by woutervanwijk** [comment]
Good suggestion!
