### ISSUE TITLE
v0.5.2 Not able to connect to Last.FM

### ISSUE THREAD

**Issue by mrWheel** [woutervanwijk/Pi-MusicBox#210]
Hi Wouter,
Thanks for the great work!!!

During startup I get the an error in the mopidy.log
"ERROR: error during last.fm setup: Invalid username. No last.fm account associated with that name."

I tripple checked the username and the password. 
Just like to mention: I have a dot "." in my password.
Regards,

**Comment by kingosticks** [comment]
Sounds like the same thing as https://github.com/woutervanwijk/Pi-MusicBox/issues/217.

**Comment by kingosticks** [comment]
Closing to track the issue in https://github.com/woutervanwijk/Pi-MusicBox/issues/217
