### ISSUE TITLE
Autoplay Url is beeing truncate

### ISSUE THREAD

**Issue by Hammarstrom** [woutervanwijk/Pi-MusicBox#229]
Hi, 
The field in settings under MusicBox for Autoplay Url has been changed (It have worked in earlier versions) and is now to short for ordinary streaming URL's eg:
 http://stream.radiohamburg.de/rhh-live/mp3-192/linkradiohamburgde/play.m3u 
will result in a 40 chr long truncated line:
http://stream.radiohamburg.de/rhh-live/m

Keep up all the good work, I have done 3 MusicBoxes :)

**Comment by kingosticks** [comment]
Sorry to palm you off but I think this issue belongs in https://github.com/woutervanwijk/mopidy-websettings
