### ISSUE TITLE
USB Audio

### ISSUE THREAD

**Issue by XDjackieXD** [woutervanwijk/Pi-MusicBox#239]
In your script you check for "usb audio" but the aplay -l output gives "USB Audio" so the detection doesn't work.
I just changed this bit of text in /opt/setsound.sh in line 61 and detection is working correctly (5min quickfix in school. We use Pi Musicbox in our classroom for everything audio releated :3).

Tested with: Pi Musicbox Beta 0.5.4 on a Pi B 512MB

Thanks for the awesome project!
-Jakob

**Comment by kingosticks** [comment]
Thanks for the report but this was fixed in https://github.com/woutervanwijk/Pi-MusicBox/commit/62d0fbcbe91a629d2bb17f0821bcbd7d4cbb2206
