### ISSUE TITLE
Locales are broken

### ISSUE THREAD

**Issue by samjuvonen** [woutervanwijk/Pi-MusicBox#249]
Version 0.5.3.

Symptom: 
Browsing tracks where filenames have non-ascii characters fails. I have a filesystem mounted with NFS4 (which really should be supported, but that's another ticket).

Fix:
apt-get install locales and restart mopidy.
dpkg-reconfigure locales doesn't seem to be needed, /etc/default/locale sets it to en_US.UTF-8 already.

Locales package should be installed by default.

**Comment by kingosticks** [comment]
https://github.com/woutervanwijk/Pi-MusicBox/issues/242
