### ISSUE TITLE
USB audio broken on 0.5.4beta

### ISSUE THREAD

**Issue by coreyk** [woutervanwijk/Pi-MusicBox#251]
Fresh install of 0.5.4beta to previously working RPi 1 B with Audioquest Dragonfly USB DAC
Automatic audio selection does not output to USB out. 
Selecting USB audio and rebooting causes GUI to not load and http://musicbox.local to be unresponsive, though I can still ssh into the Pi.
lsusb shows Dragonfly

**Comment by kingosticks** [comment]
Please replace setsound with the fixed version. Details at https://github.com/woutervanwijk/Pi-MusicBox/issues/216#issuecomment-75832516

If it's still an issue then post the output of 'aplay -l'.

**Comment by nilicule** [comment]
Cheers, was having the same problem with my USB audio, though manually setting USB didn't cause my PMB to become unresponsive.

Will give this a try and report back.

**Comment by kingosticks** [comment]
I'm a bit puzzled why it would become unresponsive, it should have just
used analog and got on with things.

**Comment by nilicule** [comment]
The proposed fix indeed fixes the problem, @kingosticks

**Comment by coreyk** [comment]
Yes, this fixes the issue of the USB sound card not working.
The webclient not loading must have been due to the apt-get update I tried before starting fresh.

**Comment by kingosticks** [comment]
If you want to use the alsamixer you need to configure it for your particular device. Nothing we can do here.
