### ISSUE TITLE
Bug 183 is back in 0.5.4beta - streamuris.js not loaded

### ISSUE THREAD

**Issue by coreyk** [woutervanwijk/Pi-MusicBox#252]
https://github.com/woutervanwijk/Pi-MusicBox/issues/183

symlink was already in place, didn't work.
deleted and recreated symlink, still reverted to default stream list.

copied my streamuris.js over /opt/webclient/js/streamuris.js and /opt/defaultwebclient/js/streamuris.js and now my streams appear in the webclient

**Comment by kingosticks** [comment]
The symlink is there (and you say) and it works as symlinks always work.  Can you please make sure you deleted your cookies after copying over your custom streamuris.js. Not doing so was the only way I could recreate the behaviour you describe.
