### ISSUE TITLE
Infinite loop searching local files.

### ISSUE THREAD

**Issue by totalrisp** [woutervanwijk/Pi-MusicBox#263]
in version 0.6RC do: search, local files, search anything 
-> infinite "loading data from musicbox..".

This was not the case in 0.53, where specifying only local as opposed to "all services" was significantly much faster (almost immediate).

**Comment by kingosticks** [comment]
Do you see any errors in /var/log/mopidy/mopidy.log?

**Comment by totalrisp** [comment]
No, at least not at the moment when the button is pressed. Of course, since this is essentially infinite, perhaps if I waited more, then at some point  stuff would appear?

**Comment by totalrisp** [comment]
This issue is due to not having the latest SQLite extension instaslled. resolved.

**Comment by kingosticks** [comment]
Excellent!
