### ISSUE TITLE
0.6 RC: Settings, WiFi Password allows only 40 characters

### ISSUE THREAD

**Issue by GitMeOn** [woutervanwijk/Pi-MusicBox#267]
But WPA2 allows Passwords up to 64 characters.
Expand the Input field to 64 characters.

**Comment by butterkekstorte** [comment]
+1 Needed to manually enter my pass in the config... Took me a long time to realize that...

**Comment by kingosticks** [comment]
This was an issue in the websettings project. It was kindle fixed in https://github.com/woutervanwijk/mopidy-websettings/pull/11.
