### ISSUE TITLE
[Request] Mixcloud support

### ISSUE THREAD

**Issue by JoeMatt** [woutervanwijk/Pi-MusicBox#272]
Mixcloud.com support would be great. A lot of my favorite users to follow are jumping ship from Soundcloud to Mixcloud due to the new overzealous copyright detection system of Soundcloud.

**Comment by kingosticks** [comment]
Unfortunately not: https://github.com/mopidy/mopidy/issues/957

https://discuss.mopidy.com/t/integrate-mixcloud-through-soundtomp3/338/1 might also be relevant. Either way, it's a Mopidy issue rather than a musicbox one.
