### ISSUE TITLE
Mopify Web Client

### ISSUE THREAD

**Issue by hkultraman** [woutervanwijk/Pi-MusicBox#275]
Hi,

I would like to use Mopify as web client. But can't find any instruction on it. I am now using stable version of Pi MusicBox 0.6

Can anyone point me to where can i find the instruction to use Mopify on Pi MusicBox Stable v0.6

Link to Mopify: https://github.com/dirkgroenen/mopidy-mopify

Many thanks.

Cheers
Michael

**Comment by kingosticks** [comment]
I think you must mean version 0.6. Mopify is a bit of a special case right now due to the way it's implemented. It should be fixed in the next version but until then you can try the following (untested by me) commands from the wiki:
```
sed -i 's/static_dir \=.*/static_dir = \/opt\/webclient/g' /boot/config/settings.ini
rm /opt/webclient
mkdir /opt/webclient
echo -e "<html><head><meta http-equiv=\"refresh\" content=\"0; URL=/musicbox_webclient/index.html\"></head><body>Web interface moved, <a href=\"/musicbox_webclient/index.html\">click here</a></body></html>" > /opt/webclient/index.html
```

But replace `musicbox_webclient/index.htm` with `mopify/index.htm`, or whatever the correct url is.

**Comment by hkultraman** [comment]
yup, i mean 0.6 (i have updated my post).

BTW, from mopify, they states it requires:

- Mopidy 1.0
- Mopidy-Spotify 1.3 (or higher)
- enabled the HTTP Extension.

Are these 3 thing already included / enabled in v0.6?

Many thanks.

Cheers

**Comment by kingosticks** [comment]
Ahh, Yeh I forgot that slight issue. We don't support mopidy v1.0 yet. If
you install the latest version of mopify it will pull in mopidy 1.0 and
then some things will not work.

However, I think there is already an older version of mopify installed by
default which should be compatible with our 0.19.5 version of mopidy. Or
you can identify and manually install an older version of mopify that
doesn't require mopidy v1.0. Something like `pip install
mopify=some-old-version-number`.

**Comment by kingosticks** [comment]
And i of course meant `pip install mopidy-mopify=some-old-version-number`

**Comment by hkultraman** [comment]
So, what is the version of mopidy come with Pi MusicBox 0.6?

Thanks.

**Comment by kingosticks** [comment]
0.19.5

**Comment by hkultraman** [comment]
And v0.6 doesn't include Mopidy-Spotify, isn't it?

many thanks.

**Comment by kingosticks** [comment]
Yes it does. Mopidy-spotify has always been included.

**Comment by kingosticks** [comment]
If you have access to your system just run `mopidy deps` to see what's included and what versions.

**Comment by hkultraman** [comment]
Many thanks, cheers.

**Comment by kingosticks** [comment]
Supporting webapp style webclients is tracked at https://github.com/woutervanwijk/Pi-MusicBox/issues/276

**Comment by tatoosh** [comment]
Is Mopidy-Mopify now running?
I tryed myself but it did not work :(

**Comment by hkultraman** [comment]
Try http://[your_ip]/mopify

**Comment by tatoosh** [comment]
it's not working :(

2015-04-26 15:11 GMT+02:00 hkultraman <notifications@github.com>:

**Comment by kingosticks** [comment]
@tatoosh please can you be clearer about what exactly you have done and what exactly is the error/problem.

**Comment by tatoosh** [comment]
@kingosticks:
I wantet to install https://github.com/mopidy/mopidy-spotify. But i think it is not compatible. Will you add this!?

**Comment by kingosticks** [comment]
As I mentioned previously in this thread, mopidy-spotify has always been a part of Pi-Musicbox. You do not need install anything extra.

**Comment by kingosticks** [comment]
Since we already have https://github.com/woutervanwijk/Pi-MusicBox/issues/276 to address the more general case there doesn't seem to be anything else to do here.
