### ISSUE TITLE
0.6RC: /music directory owned by 1000:1000

### ISSUE THREAD

**Issue by tcmb** [woutervanwijk/Pi-MusicBox#277]
Hi,

I've flashed the [0.6RC image](https://github.com/woutervanwijk/Pi-MusicBox/releases/tag/v0.6.0RC) and noticed that the `/music` directory is owned by uid and gid 1000. Both user and group with this id don't exist in `/etc/passwd` and `/etc/group`, respectively.

I asked about this in the [mopidy forum](https://discuss.mopidy.com/t/music-directory-owned-by-uid-1000-and-gid-1000/693) and was redirected here.

Thanks,
Florian

**Comment by kingosticks** [comment]
I'm not sure why this is. [The creation script does explicitly set this](https://github.com/woutervanwijk/Pi-MusicBox/blob/develop/create_musicbox.sh#L98).

**Comment by kingosticks** [comment]
I'm putting this down to a mistake during image creation. Shouldn't happen next time...
