### ISSUE TITLE
Add context menu to browse entries

### ISSUE THREAD

**Issue by joh-klein** [woutervanwijk/Pi-MusicBox#279]
I always miss the option to add browse entries (from spotify or other sources) to the queue like there is with search results.

**Comment by kingosticks** [comment]
This was fixed in the webclient in https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/pull/82

**Comment by joh-klein** [comment]
Since I checked yesterday with v 0.6.0. When (roughly) is this fix going to be in the master branch of the PI-MusicBox?

**Comment by kingosticks** [comment]
I'm afraid I really don't know what the next Musicbox release will be. But if you want, you could update to the latest development version of the webclient with `pip install -U https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/archive/develop.zip`. It should be stable.
