### ISSUE TITLE
Howto connect musicbox to Bluetooth ?

### ISSUE THREAD

**Issue by Dvsat** [woutervanwijk/Pi-MusicBox#280]
After installing a bluetooth-dongle for transmitting bluetooth to my speakers it works with testing of this lines;
~# sudo apt-get install cmus
~# dsp.alsa.device bluetooth
~# output plugin alsa
~# mpg321 -a bluetooth -g 95 http://icecast.omroep.nl/radio2-bb-mp3

Installing the latest line into rc.local starts my bluetooth speakers with the radio2 stream  ( mpg321 -a bluetooth -g 95 http://icecast.omroep.nl/radio2-bb-mp3 & ).
But where and how can I'll bring or change the lines//command with ( ~# dsp.alsa.device bluetooth
and ~# output plugin alsa ), so that MusicBox-audio output starts with Bluetooth transmit ?

**Comment by kingosticks** [comment]
HI,
I'm sorry but we don't support bluetooth streaming and this is well beyond the current scope of the project. I would suggest you try posting this at discuss.mopidy.com for a better chance of an answer. You may also find other posts regarding bluetooth streaming on there.
