### ISSUE TITLE
Playing youtube medie takes long time

### ISSUE THREAD

**Issue by ccztux** [woutervanwijk/Pi-MusicBox#292]
Hi!

First of all: Great work!

Unfortunately if i want to play youtube media, it takes a long time, till it begans to play. Is musicbox buffering the whole youtube media before playing it?

Best regards,

ccztux

**Comment by kingosticks** [comment]
This might be due to https://github.com/mopidy/mopidy/issues/1041 which is fixed in the latest Mopidy. I'm currently working on a new Musicbox release that uses all the latest versions of everything.
