### ISSUE TITLE
Add Spotify Connect support

### ISSUE THREAD

**Issue by psych0d0g** [woutervanwijk/Pi-MusicBox#294]
Now that there is a arm6hf library i would request native support for spotify connect.

https://developer.spotify.com/technologies/libspotify/#download

That way i could controll the spotify playback from my android spotify app without the ugly workaround im doing atm:

root device
Use bubbleupnp Licensed version
Install xposed framework
enable bubbleupnp xposed module
start playback from spotify on android phone

Here the audio gets captured by the xposed bubbleupnp module and streamed to musicbox via upnp which introduces alot of audio latency and way more load on my android device (thus reducing battery life) than when using native spotify connect

**Comment by kingosticks** [comment]
That library was released quite some time ago. Libspotify does not, and
will not, feature Spotify connect. Only Spotify partners have access to
spotify connect.  There is an effort to reverse engineer it by some people
but that's very unlikely to make it into pyspotify anytime soon.
