### ISSUE TITLE
Suggestion: Update master branch and tag on each release

### ISSUE THREAD

**Issue by DavisNT** [woutervanwijk/Pi-MusicBox#302]
Could it be possible to update master branch and create a tag on each release  (e.g. use GitFlow as described in http://nvie.com/posts/a-successful-git-branching-model/ )?

**Comment by kingosticks** [comment]
Yep, had meant to do it. Will certainly do it going forward.

**Comment by DavisNT** [comment]
Thanks! :smile:

**Comment by kingosticks** [comment]
Don't think we really need this to be kept open.
