### ISSUE TITLE
0.4alpha - ssh iptables rule added and then removed

### ISSUE THREAD

**Issue by scibi** [woutervanwijk/Pi-MusicBox#39]
When ssh is enabled in settings.ini the ssh daemon is started in rc.local, then proper iptables rule is made. Unfortunately after that /etc/network/if-up.d/iptables is run (at least in my setup with wifi and no ethernet). This file simple restores rules from /etc/firewall/musicbox_iptables and there is no ssh rule.

**Comment by porjo** [comment]
I've just hit this issue in 0.7.0RC5 - `/etc/network/if-up.d/iptables` being run with a ruleset that doesn't include SSH port

@woutervanwijk what change did you make to fix this issue?

**Comment by kingosticks** [comment]
How have you verified that the ssh port isn't in the allowed ports? I'm surprised to hear this is still an issue here.

**Comment by porjo** [comment]
This is the ruleset that was being loaded
```
root@MusicBox:/usr/local# cat /etc/firewall/musicbox_iptables
# MusicBox Firewall
*filter
:INPUT DROP [1:72]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [15:2194]
-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -j ACCEPT
#
# samba 137, 138 UDP (netbios-ns), 139 (TCP, smb) 445 (TCP, microsoft domainservice)
# HTTP(s): 80, 443
# DNS: 67, 68
# zeroconf: 5353
-A INPUT -p tcp -m multiport --dports 80,139,443,445 -j ACCEPT
-A INPUT -p udp -m multiport --dports 67,68,137,138,5353 -j ACCEPT
#
# Mopidy: 6600 (MPD), 6680 (HTTP)
# DAAP: 3689
# RTSP: 554
-A INPUT -p tcp -m multiport --dports 554,6600,6680,3689 -j ACCEPT
-A INPUT -p udp -m multiport --dports 554 -j ACCEPT
#
# shairport-sync
-A INPUT -p tcp -m multiport --dports 5000 -j ACCEPT
-A INPUT -p udp -m multiport --dports 6000:6101 -j ACCEPT
#
# upmpdcli
-A INPUT -p tcp -m multiport --dports 49152 -j ACCEPT
-A INPUT -p udp -m multiport --dports 1900 -j ACCEPT
#
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
COMMIT
```

**Comment by kingosticks** [comment]
Right, but the rules are modified during boot. Specifically https://github.com/pimusicbox/pimusicbox/blob/develop/filechanges/opt/musicbox/startup.sh#L192

You would need to dump the loaded rules rather than output that file.

**Comment by porjo** [comment]
Isn't that what #435 is about - some kind of race condition where the default rules override the modifed rules? I just know that I was unable to SSH in until I stopped that ruleset being loaded...

**Comment by kingosticks** [comment]
OK thanks. Wait for network is supposed to prevent that, I assume you are
using that option. I will try to look into the suggested fix from the issue
on the weekend. Thanks for taking the time to report this.
