### ISSUE TITLE
Queue issues

### ISSUE THREAD

**Issue by kristoferahlqvist** [woutervanwijk/Pi-MusicBox#47]
Hi I am having some issues with the spotify queue and shuffle.

If shuffle is activated and I choose "play track next" the song does not get played next.
And if i choose "play track" in the queue the song that I choose does not play but another

**Comment by kingosticks** [comment]
It's worth noting there's a difference between shuffle (up and down arrow, left-most icon) and random (crossing arrows, right-most icon) modes. Either way, this works for me now so it must have been fixed at some point.
