### ISSUE TITLE
please update the latests release to 0.7.0RC7 on pimusicbox.com

### ISSUE THREAD

**Issue by kdssoftware** [woutervanwijk/Pi-MusicBox#514]
Hi, 
I found pimusicbox from pimusicbox.com, installed the latest release from there (which was 0.7.0RC6), it gave a lot of playback problems. after figuring out that it wasn't the latest release I've installed 0.7.0RC7 from github. everything worked perfect from the start.
Maybe update the link on pimusicbox.com, so others won't have the same problem as me?

kind regards.

**Comment by kingosticks** [comment]
Thanks, I forgot, apologies. But I am glad rc7 works better.

**Comment by kingosticks** [comment]
Fixed in https://github.com/pimusicbox/pimusicbox.github.io/commit/cab5daf16667176db0ba3bb7f5f807ecd81fdfdb
