### ISSUE TITLE
why remove apt and ability to add / update packages

### ISSUE THREAD

**Issue by jacksnodgrass** [woutervanwijk/Pi-MusicBox#518]
We can ssh to the raspberry pi... Why not allow us to add / update packages using apt?  Is there a version of PiMusicBox that doesn't cripple the Raspbian part of the software this this is based on? 

Are you trying to save space on the SD card or not allow updates to ease support issues?  

- jack

**Comment by kingosticks** [comment]
You can do it if you really want, there is nothing stopped you from doing `apt-get update && apt-get upgrade` except that new versions of software are obviously different. This has nothing to do with saving space on the SD card.

Things are designed to work together with the versions we have, anything else usually breaks. Can you imagine a situation where everyone was doing this and then asking for help why nothing worked?
