### ISSUE TITLE
add support for Amazon Music

### ISSUE THREAD

**Issue by Dome2075** [woutervanwijk/Pi-MusicBox#536]
Is it possible to add suport for Amoazon Music?
or is there any addon for this?

Tanks

Dominik

**Comment by kingosticks** [comment]
Hi, I don't believe there is a Mopidy extension for playing music from Amazon prime, last time I looked they didn't provide an API that allowed streaming. There might be more up to date info at https://discourse.mopidy.com/search?q=Amazon
