### ISSUE TITLE
Playback stalls when playing the BBC's 320kbps (AAC-LC) radio streams

### ISSUE THREAD

**Issue by sharkeypatrick** [woutervanwijk/Pi-MusicBox#538]
I'm using a Pi Zero with Pi Musicbox
Playback stalls after a few seconds when playing the BBC radio streams:- 

http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_radio_three.m3u8

**Comment by kingosticks** [comment]
I think that's cause those are HLS streams and Mopidy 1.1 has issues with HLS streams. It is a bug, but I don't have the time to spend on PIMusicbix right now so I'm afraid I can only suggest you find alternate BBC streams. I'm sorry I don't have an specific alternate one for you to use.

**Comment by sharkeypatrick** [comment]
no worries, thanks for the clarification - much appreciated.
