### ISSUE TITLE
Can Pi Musicbox be connected to the Amazon alexa app ?

### ISSUE THREAD

**Issue by tidann** [woutervanwijk/Pi-MusicBox#540]
I want to setup a multiroom system with my amazon Echo and my raspberry pi. To do that I have to connect it to the Amazon alexa app, but is it compatible with pi musicbox ? If not, is there any alternative ?

**Comment by kingosticks** [comment]
I have no idea I'm afraid. You could try asking in the user forum, more likely to find an answer there.
