### ISSUE TITLE
pimusicbox not booting on Pi4

### ISSUE THREAD

**Issue by hessercan** [woutervanwijk/Pi-MusicBox#556]
I imaged the SD card as instructed but the pi will not boot. No display output.

**Comment by kingosticks** [comment]
Hi, please note that Pi MusicBox does NOT currently support the Raspberry Pi 4. And since this project is essentially unmaintained I don't expect that to change.

**Comment by kingosticks** [comment]
See https://github.com/pimusicbox/pimusicbox/issues/529
