### ISSUE TITLE
I can't get this to work on the Raspberry Pi Zero W 2?

### ISSUE THREAD

**Issue by cgchris99** [woutervanwijk/Pi-MusicBox#557]
Anyway to get this to run on the PI Zero W 2?

**Comment by nepozs** [comment]
Try this (copying .dtb file):
https://forums.raspberrypi.com/viewtopic.php?t=322744&start=25
untested but may work.

**Comment by jarethmt** [comment]
Just tested this out, can confirm that it does NOT work unfortunately. Anyone else have any ideas? Very unfortunate that this project seems dead and doesn't support a lot of the modern hardware :(

**Comment by kingosticks** [comment]
Yes, it is dead. Hardware support stopped at 3B. If you want to discuss workarounds I think the [forum](https://discourse.mopidy.com/t/pimusicbox-pizero2w-support/5258/5) might be more appropriate, although I don't know of a working solution there yet either.

**Comment by jarethmt** [comment]
I'm actually working on it right now... not sure what I'll get to, but I'm like, 3/4 of the way through the script already.
