### ISSUE TITLE
How to use Multi Room Audio?

### ISSUE THREAD

**Issue by gazambuja** [woutervanwijk/Pi-MusicBox#67]
Hi, I installed my Pi-MusicBox and is working fine, now, I want to sink my PC audio with rPi... in other words, I want listen my videos and other audio in PC speaker and (at the same time) in Pi-MusicBox.

How Multi room audio works?
Can I use PulseAudio sink?

In my PC I use Ubuntu 12.04

Thanks in advance!

**Comment by a-x-** [comment]
Is it still has not synchronized multiroom feature? I see, you use shairport-sync under the hood

**Comment by a-x-** [comment]
If it has now, can it be drop in replacement to shairport-sync? I want to add mpd interface along airplay. So I will be able to use home assistant tts, not only phone/macbook

**Comment by kingosticks** [comment]
Correct. No change. Some people have added snapcast to achieve this.

**Comment by a-x-** [comment]
If it can be, then am I right that I can build image and run it instead of shairport-sync w/o reinstallation the OS?

**Comment by a-x-** [comment]
Oh…
thank you
