### ISSUE TITLE
Hostname truncation - need documentation or longer hostname option

### ISSUE THREAD

**Issue by lsblakk** [woutervanwijk/Pi-MusicBox#70]
I just set up my first pimusicbox (and thank you, it was very very easy to do) but in the settings.ini file I was not told that there was a character limit for the musicbox's name - I put in 'livingroom' and discovered that it actually booted up and hosts as livingroo.local so perhaps just a note in the settings.ini file saying there's a length restriction OR make it possible to use longer host names.

**Comment by kingosticks** [comment]
The comment at https://github.com/woutervanwijk/Pi-MusicBox/blob/master/filechanges/opt/musicbox/startup.sh#L55 says this is due to a netbios name length restriction. Needs some investigating
