### ISSUE TITLE
No connection to Spotify

### ISSUE THREAD

**Issue by PrinzeFlo** [woutervanwijk/Pi-MusicBox#98]
Hey,

I installed the MusicBox on my Raspberry but i don't get connected to Spotify. I'm logged in to Spotify via Facebook and I tried it with my E-Mail and the number i got from Spotify and the Passwords from Facebook and also the Device Password i set in Spotify but it doesn't work...

Can anybody help me?

Thanks to everyone who wants to help

**Comment by cukabeka** [comment]
Sorry, i don't get it. I can login on spotify.com only via facebook connect. 

How can I determine my mighty "Spotify device username"? 
The following things don't work:
- The Spotify User Number (e.g. 114890088)
- The facebook User Name (e.g. "Foo Bar")
- The facebook registered mail (e.g. foo@bar.com)

What can I put in there?

**Comment by cukabeka** [comment]
OK, I think I found the solution. You need to go to https://www.spotify.com/account/set-device-password/ on your spotify account to set a device password. Maybe you could include that in the docs ;)
